// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt4tTraM9TJSjZ_K2J8y6dqOL70cZX85Q',
    appId: '1:983965105255:web:1a3a6394eafd9cacda28c2',
    messagingSenderId: '983965105255',
    projectId: 'noteapp-f5236',
    authDomain: 'noteapp-f5236.firebaseapp.com',
    storageBucket: 'noteapp-f5236.firebasestorage.app',
    measurementId: 'G-6RY6CSS8VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH6UhnavCyLiHRV1Mm5F-FaHqe28IpeUY',
    appId: '1:983965105255:android:9dd3acbb64a4fb2eda28c2',
    messagingSenderId: '983965105255',
    projectId: 'noteapp-f5236',
    storageBucket: 'noteapp-f5236.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4kgf8t7Yk-_UnYQoPqcBmMbYK24UOn3s',
    appId: '1:983965105255:ios:6672f1c198748bb7da28c2',
    messagingSenderId: '983965105255',
    projectId: 'noteapp-f5236',
    storageBucket: 'noteapp-f5236.firebasestorage.app',
    iosBundleId: 'com.example.noteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4kgf8t7Yk-_UnYQoPqcBmMbYK24UOn3s',
    appId: '1:983965105255:ios:6672f1c198748bb7da28c2',
    messagingSenderId: '983965105255',
    projectId: 'noteapp-f5236',
    storageBucket: 'noteapp-f5236.firebasestorage.app',
    iosBundleId: 'com.example.noteapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt4tTraM9TJSjZ_K2J8y6dqOL70cZX85Q',
    appId: '1:983965105255:web:d894c67821d638cfda28c2',
    messagingSenderId: '983965105255',
    projectId: 'noteapp-f5236',
    authDomain: 'noteapp-f5236.firebaseapp.com',
    storageBucket: 'noteapp-f5236.firebasestorage.app',
    measurementId: 'G-P2J5DGK84D',
  );
}
